.PHONY: clean All

All:
	@echo "----------Building project:[ Netflix - Debug ]----------"
	@cd "Netflix" && $(MAKE) -f  "Netflix.mk"
clean:
	@echo "----------Cleaning project:[ Netflix - Debug ]----------"
	@cd "Netflix" && $(MAKE) -f  "Netflix.mk" clean
