.PHONY: clean All

All:
	@echo "----------Building project:[ Ordenacao - Debug ]----------"
	@cd "Ordenacao" && $(MAKE) -f  "Ordenacao.mk"
clean:
	@echo "----------Cleaning project:[ Ordenacao - Debug ]----------"
	@cd "Ordenacao" && $(MAKE) -f  "Ordenacao.mk" clean
